### ISSUE TITLE
Error when try to get access from facebook backend

### ISSUE THREAD

**Issue by gelog93** [PhilipGarnero/django-rest-framework-social-oauth2#5] opened 2015-06-04 22:43 UTC
Hello
first of all thank @PhilipGarnero  for your great library. I read about and i love it but i get this error:
  {"detail":"Invalid token header. Invalid backend" } when i run follow command: 
 curl -H "Authorization: Bearer facebook user_access_token" http://localhost:8000/auth/convert-token 
Please help me i try to solve this error since 3 days but i fail. please i need your help @PhilipGarnero

**Comment by PhilipGarnero** [comment] 2015-06-04 23:02
This is because python social auth couldn't find the backend.
Have you got these lines in your `settings.py` ?
```
AUTHENTICATION_BACKENDS = (
    # Facebook OAuth2
    'social.backends.facebook.FacebookAppOAuth2',
    'social.backends.facebook.FacebookOAuth2',

    'rest_framework_social_oauth2.backends.DjangoOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)
```

**Comment by gelog93** [comment] 2015-06-04 23:20
yes i did it but nothing work

**Comment by PhilipGarnero** [comment] 2015-06-04 23:22
Can you show me your settings ?

**Comment by gelog93** [comment] 2015-06-04 23:28
@PhilipGarnero  You can see my settings bellow

"""
Django settings for flirt project.


DEBUG = True

#TEMPLATE_DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'oauth2_provider',
    'social.apps.django_app.default',
    'rest_framework_social_oauth2',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.gis',
    'rest_framework',

)

MIDDLEWARE_CLASSES = (
   
    'social.apps.django_app.middleware.SocialAuthExceptionMiddleware',
)

WSGI_APPLICATION = 'flirt.wsgi.application'


AUTHENTICATION_BACKENDS = (

    'oauth2_provider.backends.OAuth2Backend',

    # Facebook OAuth2
    'social.backends.facebook.FacebookAppOAuth2',
    'social.backends.facebook.FacebookOAuth2',

    #django social rest
    'rest_framework_social_oauth2.backends.DjangoOAuth2',

    'django.contrib.auth.backends.ModelBackend',
)


TEMPLATE_CONTEXT_PROCESSORS = (
    'django.contrib.auth.context_processors.auth',
    'social.apps.django_app.context_processors.backends',
    'social.apps.django_app.context_processors.login_redirect',
)


SOCIAL_AUTH_ADMIN_USER_SEARCH_FIELDS = [ 'username', 'first_name']


SOCIAL_AUTH_FACEBOOK_KEY = '1444690159152044'
SOCIAL_AUTH_FACEBOOK_SECRET = '**********************'

SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']

#rest api

LOGIN_REDIRECT_URL = '/users/'

OAUTH2_PROVIDER = {

     # this is the list of available scopes
     'SCOPES': {'read': 'Read scope', 'write': 'Write scope', 'groups': 'Access to your groups'},

#     'CLIENT_ID_GENERATOR_CLASS': 'oauth2_provider.generators.ClientIdGenerator',
}

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
        #'rest_framework.permissions.IsAuthenticated'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.ext.rest_framework.OAuth2Authentication',
        'rest_framework_social_oauth2.authentication.SocialAuthentication',
    ),
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler'
}

**Comment by PhilipGarnero** [comment] 2015-06-04 23:52
I don't see any problem with your configuration...
Can you try with "Django" instead of "facebook"  to see if you're getting the same error ?
If that's the case open `your_virtualenv/lib/python2.7/site-packages/rest_framework_social_oauth2/authentication.py` and print token and backend lines 47-48.

**Comment by gelog93** [comment] 2015-06-05 00:07
@PhilipGarnero I've already done it and i get  for token: b'user_access_token'
and for backend i get value :   b'facebook'

**Comment by PhilipGarnero** [comment] 2015-06-05 00:20
In django shell try this and see if it returns the facebook backend:
$./manage.py shell
>>> from social.backends.utils import load_backends
>>> from django.conf import settings
>>> load_backends(settings.AUTHENTICATION_BACKENDS)
{'facebook': <class 'social.backends.facebook.FacebookOAuth2'>, 'facebook-app': <class 'social.backends.facebook.FacebookAppOAuth2'>, 'Django': <class 'rest_framework_social_oauth2.backends.DjangoOAuth2'>}

**Comment by gelog93** [comment] 2015-06-05 00:39
@PhilipGarnero yes i tried it and it returns the facebook backend

**Comment by PhilipGarnero** [comment] 2015-06-05 00:44
Try this now
```
$./manage.py shell
from django.conf import settings
from social.backends.utils import load_backends, get_backend
get_backend(load_backends(settings.AUTHENTICATION_BACKENDS), "facebook")
<class 'social.backends.facebook.FacebookOAuth2'>
```

**Comment by gelog93** [comment] 2015-06-05 00:50
@PhilipGarnero i tried it and it return <code> class 'social.backends.facebook.FacebookOAuth2' </code>properly

**Comment by PhilipGarnero** [comment] 2015-06-05 00:54
I really have no clue then ... Everything seems to be ok.
Try to debug in `your_virtualenv/lib/python2.7/site-packages/rest_framework_social_oauth2/authentication.py` and see if you can reproduce this in the shell.
I'll let this issue opened until you manage to make some progress. Don't hesitate to ask questions if you need help.

**Comment by gelog93** [comment] 2015-06-05 01:00
Ok, thank for consecrated me your precious time. I continue to search a way for solve this issue

**Comment by PhilipGarnero** [comment] 2015-06-05 14:54
@gelog93 I was thinking, if your project is not private and doesn't contain sensitive data, you can send it to me and I'll try to figure out what is going on exactly.

**Comment by gelog93** [comment] 2015-06-07 05:56
@PhilipGarnero Sorry for late. I've created minimal project and run curl command on but i get same error so i've created new repository where i've put this project. You can find it at https://github.com/gelog93/auth/archive/master.zip please download it. i'm so hopeless

**Comment by PhilipGarnero** [comment] 2015-06-07 11:39
@gelog93 I tried your setup with a virtualenv and just ran pip install django-rest-framework-social-oauth2 to install everything. I also replace your postgre db to an sqlite and replaced your facebook app id and secret and everything worked as expected.
I think you must have misconfigured your facebook app or your python environment but this has nothing to do with this package.
Make sure you're using a virtualenv and that your app config is correct.
I can't help you much more on this :/

**Comment by gelog93** [comment] 2015-06-07 13:36
@PhilipGarnero what's python version do you use ?

**Comment by PhilipGarnero** [comment] 2015-06-07 13:53
I'm using python2.7.3

**Comment by gelog93** [comment] 2015-06-07 14:05
maybe python version is the problem because i use python 3.4

**Comment by gelog93** [comment] 2015-06-07 15:28
please can you test the app with my fb app id an secret ? with follow token ?

<code>CAAUh8COZCK6wBAFZBo9R4BbBpKJJhRpnvxGzJSZAwZBo3H8FVUOvZBEO1MkFJIjurZCS7nosZAO3OaPUEM5jhWfZBZBEvn6dlKKrZAVZAzaNRw4VhFeJftuAFdxgulAWnAgw7VDOIAAM2cd0kST8lYw7kQtHO202BErGsheZBc5bsVqFfQiSGfK2Pj7U9CHlrcfgCZAwvrLZAOu1IV7gGghhxWzZBa5</code>

**Comment by PhilipGarnero** [comment] 2015-06-07 15:29
I managed to reproduce the error with python 3.4. I suspect a wrong string encoding.

**Comment by gelog93** [comment] 2015-06-07 15:44
@PhilipGarnero Finally we know the cause

**Comment by PhilipGarnero** [comment] 2015-06-07 18:51
@gelog93 this should be fixed now.
I released 0.0.8.
Try it and come back here to close the issue if this works

**Comment by gelog93** [comment] 2015-06-07 20:21
Yes it work like a charm i'm so happy thank a lot @PhilipGarnero you are a good guy hope many people will use your good library

**Closed** 2015-06-07 20:21 UTC

**Comment by c0cky** [comment] 2016-05-30 19:48
```
$./manage.py shell
from social.backends.utils import load_backends
from django.conf import settings
load_backends(settings.AUTHENTICATION_BACKENDS)
{'facebook': <class 'social.backends.facebook.FacebookOAuth2'>, 'facebook-app': <class 'social.backends.facebook.FacebookAppOAuth2'>, 'Django': <class 'rest_framework_social_oauth2.backends.DjangoOAuth2'>}
```

Was really helpful for finding `google-oauth2` as the backend name for google, which wasn't obvious to me. Maybe something like this should be included in the docs so that others can quickly find out the backend names?

**Comment by PhilipGarnero** [comment] 2016-05-30 21:43
The backend names are the same one used by python social auth.
If you are interested in a backend, the best way to go is to check python social auth doc about it and maybe open the backend code for more insights.
