### ISSUE TITLE
After Convert Token, user is not logged

### ISSUE THREAD

**Issue by ballbrk** [PhilipGarnero/django-rest-framework-social-oauth2#24] opened 2015-11-05 14:48 UTC
Hi, 
I'm getting an extrange behaviour using facebook with DRF in my project.

1st)  I make the convert token and get a good response  http://www.in.usetopic.com:8000/auth/convert-token  passing the correct data

and I got this answer from our server 

{
access_token: "pdUOQx5MwoC7fKC79OXD3Fp36NkR8q"
token_type: "Bearer"
expires_in: 36000
refresh_token: "jdi9dVRYuJ59D5OF7vElQVdJmaDv0v"
scope: "read write groups"
}

This is correct, the user is created and everything is ok

2nd) 
I go to this url to get my details

curl -H "Authorization: Bearer facebook pdUOQx5MwoC7fKC79OXD3Fp36NkR8q" http://www.in.usetopic.com:8000/api/v1/user/me

or 

curl -H "Authorization: Bearer pdUOQx5MwoC7fKC79OXD3Fp36NkR8q"  http://www.in.usetopic.com:8000/api/v1/user/me

I got the same answer
{"detail":"The authentication credentials are not provided."}

**Comment by PhilipGarnero** [comment] 2015-11-06 07:10
Did you enable the authentication class ? Either globally on your project or on your view ?

**Comment by PhilipGarnero** [comment] 2015-11-06 07:13
And the first usage you're doing does not work like this. If you put facebook it has to be a facebook access token, the one you wanted to convert.

**Comment by PhilipGarnero** [comment] 2015-11-08 22:09
It seems that the problem is resolved, so I'm closing this. Feel free to reopen if that's not the case.

**Closed by PhilipGarnero** 2015-11-08 22:09 UTC
