### ISSUE TITLE
Sending multipart/form-data with Django-rest-framework 3.6.4

### ISSUE THREAD

**Issue by soloidx** [PhilipGarnero/django-rest-framework-social-oauth2#118] opened 2017-08-25 00:37 UTC
With the latest update in Django-rest-framework I cannot call to the convert-token endpoint, I made this call:

```
curl -X POST http://127.0.0.1:8000/c/auth/convert-token/ 
  -H 'accept: application/json' \
  -H 'cache-control: no-cache' \
  -H 'content-type: multipart/form-data;' \
  -F grant_type=convert_token \
  -F backend=facebook \
  -F client_id=xxx
  -F token=xxx
```

And I get the error: "AttributeError: You cannot set the upload handlers after the upload has been processed."

But if I send the data in "content-type: application/json" (with the body in JSON) works perfectly.
Doing some research it seems that the error it's started in https://github.com/PhilipGarnero/django-rest-framework-social-oauth2/blob/master/rest_framework_social_oauth2/views.py#L38 but cannot find the cause.

**Comment by PhilipGarnero** [comment] 2017-10-24 08:18
Sorry, I didn't have the time to check your issue back then.

Why are you sending multipart data ?
This implies that you're trying to upload a file thus resulting in django-rest-framework crashing because there is no file.
Have you tried `application/x-www-form-urlencoded` instead ?

Closing this for now but feel free to reopen

**Closed by PhilipGarnero** 2017-10-24 08:18 UTC

**Comment by taqi457** [comment] 2018-03-15 12:35
@soloidx, I had the same issue like this, but in my case I can confirm that it was fixed by removing the debug_toolbar which was causing the issue. Were you using something similar ?

**Comment by soloidx** [comment] 2018-03-15 13:32
@taqi457, well I just move all the client requests to simple JSON but yes, I have been using the debug toolbar in that time
